### ISSUE TITLE
Code in README

### ISSUE THREAD

**Issue by datawookie** [kushtekriwal/TwitterBot#2]
It seems that you want to include some code in your README file. You can get very nicely formatted code by using Markdown syntax. Look at [this](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

**Comment by kushtekriwal** [comment]
We thought of adding code to our README file, but was not sure on what to include. Could you please advise on what to add to it?

**Comment by datawookie** [comment]
There already is code in your README. It's just not nicely formatted. It should rather look like this:

```
library(twitteR)
library(tm)
library(wordcloud)
library(RColorBrewer)
library(ggmap)
```

**Comment by kushtekriwal** [comment]
Made necessary change.

**Comment by datawookie** [comment]
Aha! That looks much better, right?
